### ISSUE TITLE
Application startup failed InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select count(*) as col_0_0_ from rborder order0_]

### ISSUE THREAD

**Issue by Stefan-Isele** [olivergierke/spring-restbucks#22]
Entered:

`java -jar target/restbucks-1.0.0.BUILD-SNAPSHOT.war`

got:

```
2014-05-30 10:12:28,443 ERROR         org.springframework.boot.SpringApplication: 331 - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'orderInitializer' defined in URL [jar:file:C:/ws/ws-spring-restbucks/spring-restbucks/target/restbucks-1.0.0.BUILD-SNAPSHOT.war!/WEB-INF/classes!/org/springsource/restbucks/order/OrderInitializer.class]: Instantiation
of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springsource.restbucks.order.OrderInitializer]: Constructor threw exception; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select count(*) as col_0_0_ from rborder order0_]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:278) ~[spring-beans-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1114) ~[spring-beans-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1017) ~[spring-beans-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504) ~[spring-beans-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475) ~[spring-beans-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304) ~[spring-beans-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300) ~[spring-beans-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195) ~[spring-beans-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703) ~[spring-beans-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760) ~[spring-context-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482) ~[spring-context-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:120) ~[spring-boot-1.1.0.M2.jar!/:1.1.0.M2]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:683) [spring-boot-1.1.0.M2.jar!/:1.1.0.M2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) [spring-boot-1.1.0.M2.jar!/:1.1.0.M2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:944) [spring-boot-1.1.0.M2.jar!/:1.1.0.M2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:933) [spring-boot-1.1.0.M2.jar!/:1.1.0.M2]
        at org.springsource.restbucks.Restbucks.main(Restbucks.java:52) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_51]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_51]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) [restbucks-1.0.0.BUILD-SNAPSHOT.war:na]
        at java.lang.Thread.run(Unknown Source) [na:1.7.0_51]
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.springsource.restbucks.order.OrderInitializer]: Constructor threw exception; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select
count(*) as col_0_0_ from rborder order0_]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:164) ~[spring-beans-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:125) ~[spring-beans-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:270) ~[spring-beans-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        ... 23 common frames omitted
Caused by: org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select count(*) as col_0_0_ from rborder order0_]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:172) ~[spring-orm-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:155) ~[spring-orm-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:417) ~[spring-orm-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59) ~[spring-tx-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213) ~[spring-tx-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147) ~[spring-tx-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodIntercceptor.invoke(CrudMethodMetadataPostProcessor.java:111) ~[spring-data-jpa-1.6.0.RELEASE.jar!/:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at com.sun.proxy.$Proxy81.count(Unknown Source) ~[na:na]
        at org.springsource.restbucks.order.OrderInitializer.<init>(OrderInitializer.java:45) ~[classes!/:na]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_51]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_51]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_51]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.7.0_51]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148) ~[spring-beans-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        ... 25 common frames omitted
Caused by: org.hibernate.exception.SQLGrammarException: could not prepare statement
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:80) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:196) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:160) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1884) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1861) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1838) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.loader.Loader.doQuery(Loader.java:909) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.loader.Loader.doList(Loader.java:2551) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.loader.Loader.doList(Loader.java:2537) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2367) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.loader.Loader.list(Loader.java:2362) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:496) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:387) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:229) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1260) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:573) ~[hibernate-entitymanager-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.jpa.internal.QueryImpl.getSingleResult(QueryImpl.java:495) ~[hibernate-entitymanager-4.3.1.Final.jar!/:4.3.1.Final]
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.count(SimpleJpaRepository.java:357) ~[spring-data-jpa-1.6.0.RELEASE.jar!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_51]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_51]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:405) ~[spring-data-commons-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:390) ~[spring-data-commons-1.8.0.RELEASE.jar!/:na]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:344) ~[spring-data-commons-1.8.0.RELEASE.jar!/:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98) ~[spring-tx-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262) ~[spring-tx-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95) ~[spring-tx-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx-4.0.5.RELEASE.jar!/:4.0.5.RELEASE]
        ... 38 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: RBORDER
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
        at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
        at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source) ~[hsqldb-2.3.2.jar!/:2.3.2]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_51]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_51]
        at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126) ~[tomcat-jdbc-7.0.53.jar!/:na]
        at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:109) ~[tomcat-jdbc-7.0.53.jar!/:na]
        at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:80) ~[tomcat-jdbc-7.0.53.jar!/:na]
        at com.sun.proxy.$Proxy55.prepareStatement(Unknown Source) ~[na:na]
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:162) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186) ~[hibernate-core-4.3.1.Final.jar!/:4.3.1.Final]
        ... 69 common frames omitted
```

**Comment by olivergierke** [comment]
Still seeing this? Builds are green these days, closing. Feel free to reopen if necessary.
