### ISSUE TITLE
Dependency on spring-hateoas 0.17.0.BUILD-SNAPSHOT (TypeConstrainedMappingJackson2HttpMessageConverter)?

### ISSUE THREAD

**Issue by jackthecoder** [olivergierke/spring-restbucks#24]
The project did not run failing with a ClassNotFoundException:
```
Caused by: java.lang.ClassNotFoundException: org.springframework.hateoas.mvc.TypeConstrainedMappingJackson2HttpMessageConverter
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 33 more
```

Turned out the class is indeed not available for spring-hateoas 0.15.0.RELEASE, but it is available 0.17.0.BUILD-SNAPSHOT (maybe earlier). Could it be that the pom.xml of spring-restbucks needs to be updated with the right version?

**Comment by olivergierke** [comment]
This should work now as we rely on Boot's starters pulling in the correct versions.
